FROM ubuntu:20.04

RUN apt-get update              \
    && apt-get install -y       \
    nginx                       \
    unzip                       \
    php-fpm                     \
    php7.4-mbstring             \
    php7.4-xml                  \
    php7.4-bcmath               \
    php7.4-intl                 \
    php7.4-gd                   \
    php7.4-zip                  \
    php7.4-mysql


COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.4/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

CMD service php7.4-fpm start    \
    && nginx -g 'daemon off;'   \
    && bash